//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MoCSModel", "FK_TournamentAssignment_Assignment", "Assignment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MoCS.Data.Entity.Assignment), "TournamentAssignment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MoCS.Data.Entity.TournamentAssignment))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MoCSModel", "FK_AssignmentEnrollment_Team", "Team", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MoCS.Data.Entity.Team), "AssignmentEnrollment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MoCS.Data.Entity.AssignmentEnrollment))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MoCSModel", "FK_AssignmentEnrollment_TournamentAssignment", "TournamentAssignment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MoCS.Data.Entity.TournamentAssignment), "AssignmentEnrollment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MoCS.Data.Entity.AssignmentEnrollment))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MoCSModel", "FK_Submit_AssignmentEnrollment", "AssignmentEnrollment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MoCS.Data.Entity.AssignmentEnrollment), "Submit", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MoCS.Data.Entity.Submit))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MoCSModel", "FK_Submit_TournamentAssignment", "TournamentAssignment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MoCS.Data.Entity.TournamentAssignment), "Submit", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MoCS.Data.Entity.Submit))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MoCSModel", "FK_TournamentAssignment_Tournament", "Tournament", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MoCS.Data.Entity.Tournament), "TournamentAssignment", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MoCS.Data.Entity.TournamentAssignment))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MoCSModel", "FK_Submit_Team", "Team", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MoCS.Data.Entity.Team), "Submit", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MoCS.Data.Entity.Submit))]

// Original file name:
// Generation date: 29-1-2010 20:29:18
namespace MoCS.Data.Entity
{
    
    /// <summary>
    /// There are no comments for MoCSModelContainer in the schema.
    /// </summary>
    public partial class MoCSModelContainer : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MoCSModelContainer object using the connection string found in the 'MoCSModelContainer' section of the application configuration file.
        /// </summary>
        public MoCSModelContainer() : 
                base("name=MoCSModelContainer", "MoCSModelContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MoCSModelContainer object.
        /// </summary>
        public MoCSModelContainer(string connectionString) : 
                base(connectionString, "MoCSModelContainer")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MoCSModelContainer object.
        /// </summary>
        public MoCSModelContainer(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MoCSModelContainer")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Assignment in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Assignment> Assignment
        {
            get
            {
                if ((this._Assignment == null))
                {
                    this._Assignment = base.CreateQuery<Assignment>("[Assignment]");
                }
                return this._Assignment;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Assignment> _Assignment;
        /// <summary>
        /// There are no comments for AssignmentEnrollment in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<AssignmentEnrollment> AssignmentEnrollment
        {
            get
            {
                if ((this._AssignmentEnrollment == null))
                {
                    this._AssignmentEnrollment = base.CreateQuery<AssignmentEnrollment>("[AssignmentEnrollment]");
                }
                return this._AssignmentEnrollment;
            }
        }
        private global::System.Data.Objects.ObjectQuery<AssignmentEnrollment> _AssignmentEnrollment;
        /// <summary>
        /// There are no comments for Submit in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Submit> Submit
        {
            get
            {
                if ((this._Submit == null))
                {
                    this._Submit = base.CreateQuery<Submit>("[Submit]");
                }
                return this._Submit;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Submit> _Submit;
        /// <summary>
        /// There are no comments for Team in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Team> Team
        {
            get
            {
                if ((this._Team == null))
                {
                    this._Team = base.CreateQuery<Team>("[Team]");
                }
                return this._Team;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Team> _Team;
        /// <summary>
        /// There are no comments for Tournament in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<Tournament> Tournament
        {
            get
            {
                if ((this._Tournament == null))
                {
                    this._Tournament = base.CreateQuery<Tournament>("[Tournament]");
                }
                return this._Tournament;
            }
        }
        private global::System.Data.Objects.ObjectQuery<Tournament> _Tournament;
        /// <summary>
        /// There are no comments for TournamentAssignment in the schema.
        /// </summary>
        public global::System.Data.Objects.ObjectQuery<TournamentAssignment> TournamentAssignment
        {
            get
            {
                if ((this._TournamentAssignment == null))
                {
                    this._TournamentAssignment = base.CreateQuery<TournamentAssignment>("[TournamentAssignment]");
                }
                return this._TournamentAssignment;
            }
        }
        private global::System.Data.Objects.ObjectQuery<TournamentAssignment> _TournamentAssignment;
        /// <summary>
        /// There are no comments for Assignment in the schema.
        /// </summary>
        public void AddToAssignment(Assignment assignment)
        {
            base.AddObject("Assignment", assignment);
        }
        /// <summary>
        /// There are no comments for AssignmentEnrollment in the schema.
        /// </summary>
        public void AddToAssignmentEnrollment(AssignmentEnrollment assignmentEnrollment)
        {
            base.AddObject("AssignmentEnrollment", assignmentEnrollment);
        }
        /// <summary>
        /// There are no comments for Submit in the schema.
        /// </summary>
        public void AddToSubmit(Submit submit)
        {
            base.AddObject("Submit", submit);
        }
        /// <summary>
        /// There are no comments for Team in the schema.
        /// </summary>
        public void AddToTeam(Team team)
        {
            base.AddObject("Team", team);
        }
        /// <summary>
        /// There are no comments for Tournament in the schema.
        /// </summary>
        public void AddToTournament(Tournament tournament)
        {
            base.AddObject("Tournament", tournament);
        }
        /// <summary>
        /// There are no comments for TournamentAssignment in the schema.
        /// </summary>
        public void AddToTournamentAssignment(TournamentAssignment tournamentAssignment)
        {
            base.AddObject("TournamentAssignment", tournamentAssignment);
        }
    }
    /// <summary>
    /// There are no comments for MoCSModel.Assignment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MoCSModel", Name="Assignment")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Assignment : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Assignment object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="createDate">Initial value of CreateDate.</param>
        /// <param name="path">Initial value of Path.</param>
        public static Assignment CreateAssignment(int id, string name, global::System.DateTime createDate, string path)
        {
            Assignment assignment = new Assignment();
            assignment.Id = id;
            assignment.Name = name;
            assignment.CreateDate = createDate;
            assignment.Path = path;
            return assignment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property FriendlyName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyName
        {
            get
            {
                return this._FriendlyName;
            }
            set
            {
                this.OnFriendlyNameChanging(value);
                this.ReportPropertyChanging("FriendlyName");
                this._FriendlyName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("FriendlyName");
                this.OnFriendlyNameChanged();
            }
        }
        private string _FriendlyName;
        partial void OnFriendlyNameChanging(string value);
        partial void OnFriendlyNameChanged();
        /// <summary>
        /// There are no comments for Property Tagline in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Tagline
        {
            get
            {
                return this._Tagline;
            }
            set
            {
                this.OnTaglineChanging(value);
                this.ReportPropertyChanging("Tagline");
                this._Tagline = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Tagline");
                this.OnTaglineChanged();
            }
        }
        private string _Tagline;
        partial void OnTaglineChanging(string value);
        partial void OnTaglineChanged();
        /// <summary>
        /// There are no comments for Property CreateDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this.ReportPropertyChanging("CreateDate");
                this._CreateDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreateDate");
                this.OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// There are no comments for Property Path in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this._Path;
            }
            set
            {
                this.OnPathChanging(value);
                this.ReportPropertyChanging("Path");
                this._Path = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Path");
                this.OnPathChanged();
            }
        }
        private string _Path;
        partial void OnPathChanging(string value);
        partial void OnPathChanged();
        /// <summary>
        /// There are no comments for TournamentAssignment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_TournamentAssignment_Assignment", "TournamentAssignment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<TournamentAssignment> TournamentAssignment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<TournamentAssignment>("MoCSModel.FK_TournamentAssignment_Assignment", "TournamentAssignment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<TournamentAssignment>("MoCSModel.FK_TournamentAssignment_Assignment", "TournamentAssignment", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MoCSModel.AssignmentEnrollment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MoCSModel", Name="AssignmentEnrollment")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class AssignmentEnrollment : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new AssignmentEnrollment object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="startDate">Initial value of StartDate.</param>
        /// <param name="isActive">Initial value of IsActive.</param>
        public static AssignmentEnrollment CreateAssignmentEnrollment(int id, global::System.DateTime startDate, bool isActive)
        {
            AssignmentEnrollment assignmentEnrollment = new AssignmentEnrollment();
            assignmentEnrollment.Id = id;
            assignmentEnrollment.StartDate = startDate;
            assignmentEnrollment.IsActive = isActive;
            return assignmentEnrollment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property StartDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime StartDate
        {
            get
            {
                return this._StartDate;
            }
            set
            {
                this.OnStartDateChanging(value);
                this.ReportPropertyChanging("StartDate");
                this._StartDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("StartDate");
                this.OnStartDateChanged();
            }
        }
        private global::System.DateTime _StartDate;
        partial void OnStartDateChanging(global::System.DateTime value);
        partial void OnStartDateChanged();
        /// <summary>
        /// There are no comments for Property IsActive in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this.OnIsActiveChanging(value);
                this.ReportPropertyChanging("IsActive");
                this._IsActive = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsActive");
                this.OnIsActiveChanged();
            }
        }
        private bool _IsActive;
        partial void OnIsActiveChanging(bool value);
        partial void OnIsActiveChanged();
        /// <summary>
        /// There are no comments for Team in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_AssignmentEnrollment_Team", "Team")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Team Team
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Team>("MoCSModel.FK_AssignmentEnrollment_Team", "Team").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Team>("MoCSModel.FK_AssignmentEnrollment_Team", "Team").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Team in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Team> TeamReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Team>("MoCSModel.FK_AssignmentEnrollment_Team", "Team");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Team>("MoCSModel.FK_AssignmentEnrollment_Team", "Team", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TournamentAssignment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_AssignmentEnrollment_TournamentAssignment", "TournamentAssignment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public TournamentAssignment TournamentAssignment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TournamentAssignment>("MoCSModel.FK_AssignmentEnrollment_TournamentAssignment", "TournamentAssignment").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TournamentAssignment>("MoCSModel.FK_AssignmentEnrollment_TournamentAssignment", "TournamentAssignment").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for TournamentAssignment in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<TournamentAssignment> TournamentAssignmentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TournamentAssignment>("MoCSModel.FK_AssignmentEnrollment_TournamentAssignment", "TournamentAssignment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<TournamentAssignment>("MoCSModel.FK_AssignmentEnrollment_TournamentAssignment", "TournamentAssignment", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Submit in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_Submit_AssignmentEnrollment", "Submit")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Submit> Submit
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Submit>("MoCSModel.FK_Submit_AssignmentEnrollment", "Submit");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Submit>("MoCSModel.FK_Submit_AssignmentEnrollment", "Submit", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MoCSModel.Submit in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MoCSModel", Name="Submit")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Submit : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Submit object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="submitDate">Initial value of SubmitDate.</param>
        /// <param name="status">Initial value of Status.</param>
        /// <param name="secondsSinceEnrollment">Initial value of SecondsSinceEnrollment.</param>
        /// <param name="isProcessed">Initial value of IsProcessed.</param>
        /// <param name="processingDetails">Initial value of ProcessingDetails.</param>
        /// <param name="fileName">Initial value of FileName.</param>
        /// <param name="fileContents">Initial value of FileContents.</param>
        /// <param name="data">Initial value of Data.</param>
        public static Submit CreateSubmit(int id, global::System.DateTime submitDate, string status, long secondsSinceEnrollment, bool isProcessed, string processingDetails, string fileName, string fileContents, byte[] data)
        {
            Submit submit = new Submit();
            submit.Id = id;
            submit.SubmitDate = submitDate;
            submit.Status = status;
            submit.SecondsSinceEnrollment = secondsSinceEnrollment;
            submit.IsProcessed = isProcessed;
            submit.ProcessingDetails = processingDetails;
            submit.FileName = fileName;
            submit.FileContents = fileContents;
            submit.Data = data;
            return submit;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property SubmitDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime SubmitDate
        {
            get
            {
                return this._SubmitDate;
            }
            set
            {
                this.OnSubmitDateChanging(value);
                this.ReportPropertyChanging("SubmitDate");
                this._SubmitDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SubmitDate");
                this.OnSubmitDateChanged();
            }
        }
        private global::System.DateTime _SubmitDate;
        partial void OnSubmitDateChanging(global::System.DateTime value);
        partial void OnSubmitDateChanged();
        /// <summary>
        /// There are no comments for Property Status in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                this.OnStatusChanging(value);
                this.ReportPropertyChanging("Status");
                this._Status = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Status");
                this.OnStatusChanged();
            }
        }
        private string _Status;
        partial void OnStatusChanging(string value);
        partial void OnStatusChanged();
        /// <summary>
        /// There are no comments for Property SecondsSinceEnrollment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public long SecondsSinceEnrollment
        {
            get
            {
                return this._SecondsSinceEnrollment;
            }
            set
            {
                this.OnSecondsSinceEnrollmentChanging(value);
                this.ReportPropertyChanging("SecondsSinceEnrollment");
                this._SecondsSinceEnrollment = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SecondsSinceEnrollment");
                this.OnSecondsSinceEnrollmentChanged();
            }
        }
        private long _SecondsSinceEnrollment;
        partial void OnSecondsSinceEnrollmentChanging(long value);
        partial void OnSecondsSinceEnrollmentChanged();
        /// <summary>
        /// There are no comments for Property IsProcessed in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProcessed
        {
            get
            {
                return this._IsProcessed;
            }
            set
            {
                this.OnIsProcessedChanging(value);
                this.ReportPropertyChanging("IsProcessed");
                this._IsProcessed = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsProcessed");
                this.OnIsProcessedChanged();
            }
        }
        private bool _IsProcessed;
        partial void OnIsProcessedChanging(bool value);
        partial void OnIsProcessedChanged();
        /// <summary>
        /// There are no comments for Property ProcessingDetails in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string ProcessingDetails
        {
            get
            {
                return this._ProcessingDetails;
            }
            set
            {
                this.OnProcessingDetailsChanging(value);
                this.ReportPropertyChanging("ProcessingDetails");
                this._ProcessingDetails = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ProcessingDetails");
                this.OnProcessingDetailsChanged();
            }
        }
        private string _ProcessingDetails;
        partial void OnProcessingDetailsChanging(string value);
        partial void OnProcessingDetailsChanged();
        /// <summary>
        /// There are no comments for Property FileName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this._FileName;
            }
            set
            {
                this.OnFileNameChanging(value);
                this.ReportPropertyChanging("FileName");
                this._FileName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FileName");
                this.OnFileNameChanged();
            }
        }
        private string _FileName;
        partial void OnFileNameChanging(string value);
        partial void OnFileNameChanged();
        /// <summary>
        /// There are no comments for Property FileContents in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string FileContents
        {
            get
            {
                return this._FileContents;
            }
            set
            {
                this.OnFileContentsChanging(value);
                this.ReportPropertyChanging("FileContents");
                this._FileContents = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("FileContents");
                this.OnFileContentsChanged();
            }
        }
        private string _FileContents;
        partial void OnFileContentsChanging(string value);
        partial void OnFileContentsChanged();
        /// <summary>
        /// There are no comments for Property Data in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data
        {
            get
            {
                return global::System.Data.Objects.DataClasses.StructuralObject.GetValidValue(this._Data);
            }
            set
            {
                this.OnDataChanging(value);
                this.ReportPropertyChanging("Data");
                this._Data = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Data");
                this.OnDataChanged();
            }
        }
        private byte[] _Data;
        partial void OnDataChanging(byte[] value);
        partial void OnDataChanged();
        /// <summary>
        /// There are no comments for AssignmentEnrollment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_Submit_AssignmentEnrollment", "AssignmentEnrollment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public AssignmentEnrollment AssignmentEnrollment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<AssignmentEnrollment>("MoCSModel.FK_Submit_AssignmentEnrollment", "AssignmentEnrollment").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<AssignmentEnrollment>("MoCSModel.FK_Submit_AssignmentEnrollment", "AssignmentEnrollment").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for AssignmentEnrollment in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<AssignmentEnrollment> AssignmentEnrollmentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<AssignmentEnrollment>("MoCSModel.FK_Submit_AssignmentEnrollment", "AssignmentEnrollment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<AssignmentEnrollment>("MoCSModel.FK_Submit_AssignmentEnrollment", "AssignmentEnrollment", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for TournamentAssignment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_Submit_TournamentAssignment", "TournamentAssignment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public TournamentAssignment TournamentAssignment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TournamentAssignment>("MoCSModel.FK_Submit_TournamentAssignment", "TournamentAssignment").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TournamentAssignment>("MoCSModel.FK_Submit_TournamentAssignment", "TournamentAssignment").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for TournamentAssignment in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<TournamentAssignment> TournamentAssignmentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TournamentAssignment>("MoCSModel.FK_Submit_TournamentAssignment", "TournamentAssignment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<TournamentAssignment>("MoCSModel.FK_Submit_TournamentAssignment", "TournamentAssignment", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Team in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_Submit_Team", "Team")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Team Team
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Team>("MoCSModel.FK_Submit_Team", "Team").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Team>("MoCSModel.FK_Submit_Team", "Team").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Team in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Team> TeamReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Team>("MoCSModel.FK_Submit_Team", "Team");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Team>("MoCSModel.FK_Submit_Team", "Team", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MoCSModel.Team in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MoCSModel", Name="Team")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Team : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Team object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="password">Initial value of Password.</param>
        /// <param name="createDate">Initial value of CreateDate.</param>
        /// <param name="score">Initial value of Score.</param>
        /// <param name="isAdmin">Initial value of IsAdmin.</param>
        public static Team CreateTeam(int id, string name, string password, global::System.DateTime createDate, int score, bool isAdmin)
        {
            Team team = new Team();
            team.Id = id;
            team.Name = name;
            team.Password = password;
            team.CreateDate = createDate;
            team.Score = score;
            team.IsAdmin = isAdmin;
            return team;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this.ReportPropertyChanging("Password");
                this._Password = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Password");
                this.OnPasswordChanged();
            }
        }
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property Members in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Members
        {
            get
            {
                return this._Members;
            }
            set
            {
                this.OnMembersChanging(value);
                this.ReportPropertyChanging("Members");
                this._Members = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Members");
                this.OnMembersChanged();
            }
        }
        private string _Members;
        partial void OnMembersChanging(string value);
        partial void OnMembersChanged();
        /// <summary>
        /// There are no comments for Property CreateDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this.ReportPropertyChanging("CreateDate");
                this._CreateDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreateDate");
                this.OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// There are no comments for Property Score in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Score
        {
            get
            {
                return this._Score;
            }
            set
            {
                this.OnScoreChanging(value);
                this.ReportPropertyChanging("Score");
                this._Score = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Score");
                this.OnScoreChanged();
            }
        }
        private int _Score;
        partial void OnScoreChanging(int value);
        partial void OnScoreChanged();
        /// <summary>
        /// There are no comments for Property IsAdmin in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAdmin
        {
            get
            {
                return this._IsAdmin;
            }
            set
            {
                this.OnIsAdminChanging(value);
                this.ReportPropertyChanging("IsAdmin");
                this._IsAdmin = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsAdmin");
                this.OnIsAdminChanged();
            }
        }
        private bool _IsAdmin;
        partial void OnIsAdminChanging(bool value);
        partial void OnIsAdminChanged();
        /// <summary>
        /// There are no comments for AssignmentEnrollment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_AssignmentEnrollment_Team", "AssignmentEnrollment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<AssignmentEnrollment> AssignmentEnrollment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<AssignmentEnrollment>("MoCSModel.FK_AssignmentEnrollment_Team", "AssignmentEnrollment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<AssignmentEnrollment>("MoCSModel.FK_AssignmentEnrollment_Team", "AssignmentEnrollment", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Submit in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_Submit_Team", "Submit")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Submit> Submit
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Submit>("MoCSModel.FK_Submit_Team", "Submit");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Submit>("MoCSModel.FK_Submit_Team", "Submit", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MoCSModel.Tournament in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MoCSModel", Name="Tournament")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Tournament : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Tournament object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="createDate">Initial value of CreateDate.</param>
        public static Tournament CreateTournament(int id, string name, global::System.DateTime createDate)
        {
            Tournament tournament = new Tournament();
            tournament.Id = id;
            tournament.Name = name;
            tournament.CreateDate = createDate;
            return tournament;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property CreateDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this.ReportPropertyChanging("CreateDate");
                this._CreateDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreateDate");
                this.OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// There are no comments for TournamentAssignment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_TournamentAssignment_Tournament", "TournamentAssignment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<TournamentAssignment> TournamentAssignment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<TournamentAssignment>("MoCSModel.FK_TournamentAssignment_Tournament", "TournamentAssignment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<TournamentAssignment>("MoCSModel.FK_TournamentAssignment_Tournament", "TournamentAssignment", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MoCSModel.TournamentAssignment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MoCSModel", Name="TournamentAssignment")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TournamentAssignment : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TournamentAssignment object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="assignmentOrder">Initial value of AssignmentOrder.</param>
        /// <param name="points1">Initial value of Points1.</param>
        /// <param name="points2">Initial value of Points2.</param>
        /// <param name="points3">Initial value of Points3.</param>
        /// <param name="isActive">Initial value of IsActive.</param>
        /// <param name="createDate">Initial value of CreateDate.</param>
        public static TournamentAssignment CreateTournamentAssignment(int id, int assignmentOrder, int points1, int points2, int points3, bool isActive, global::System.DateTime createDate)
        {
            TournamentAssignment tournamentAssignment = new TournamentAssignment();
            tournamentAssignment.Id = id;
            tournamentAssignment.AssignmentOrder = assignmentOrder;
            tournamentAssignment.Points1 = points1;
            tournamentAssignment.Points2 = points2;
            tournamentAssignment.Points3 = points3;
            tournamentAssignment.IsActive = isActive;
            tournamentAssignment.CreateDate = createDate;
            return tournamentAssignment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property AssignmentOrder in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int AssignmentOrder
        {
            get
            {
                return this._AssignmentOrder;
            }
            set
            {
                this.OnAssignmentOrderChanging(value);
                this.ReportPropertyChanging("AssignmentOrder");
                this._AssignmentOrder = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("AssignmentOrder");
                this.OnAssignmentOrderChanged();
            }
        }
        private int _AssignmentOrder;
        partial void OnAssignmentOrderChanging(int value);
        partial void OnAssignmentOrderChanged();
        /// <summary>
        /// There are no comments for Property Points1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Points1
        {
            get
            {
                return this._Points1;
            }
            set
            {
                this.OnPoints1Changing(value);
                this.ReportPropertyChanging("Points1");
                this._Points1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Points1");
                this.OnPoints1Changed();
            }
        }
        private int _Points1;
        partial void OnPoints1Changing(int value);
        partial void OnPoints1Changed();
        /// <summary>
        /// There are no comments for Property Points2 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Points2
        {
            get
            {
                return this._Points2;
            }
            set
            {
                this.OnPoints2Changing(value);
                this.ReportPropertyChanging("Points2");
                this._Points2 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Points2");
                this.OnPoints2Changed();
            }
        }
        private int _Points2;
        partial void OnPoints2Changing(int value);
        partial void OnPoints2Changed();
        /// <summary>
        /// There are no comments for Property Points3 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public int Points3
        {
            get
            {
                return this._Points3;
            }
            set
            {
                this.OnPoints3Changing(value);
                this.ReportPropertyChanging("Points3");
                this._Points3 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Points3");
                this.OnPoints3Changed();
            }
        }
        private int _Points3;
        partial void OnPoints3Changing(int value);
        partial void OnPoints3Changed();
        /// <summary>
        /// There are no comments for Property IsActive in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this._IsActive;
            }
            set
            {
                this.OnIsActiveChanging(value);
                this.ReportPropertyChanging("IsActive");
                this._IsActive = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IsActive");
                this.OnIsActiveChanged();
            }
        }
        private bool _IsActive;
        partial void OnIsActiveChanging(bool value);
        partial void OnIsActiveChanged();
        /// <summary>
        /// There are no comments for Property CreateDate in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.DateTime CreateDate
        {
            get
            {
                return this._CreateDate;
            }
            set
            {
                this.OnCreateDateChanging(value);
                this.ReportPropertyChanging("CreateDate");
                this._CreateDate = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("CreateDate");
                this.OnCreateDateChanged();
            }
        }
        private global::System.DateTime _CreateDate;
        partial void OnCreateDateChanging(global::System.DateTime value);
        partial void OnCreateDateChanged();
        /// <summary>
        /// There are no comments for Assignment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_TournamentAssignment_Assignment", "Assignment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Assignment Assignment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Assignment>("MoCSModel.FK_TournamentAssignment_Assignment", "Assignment").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Assignment>("MoCSModel.FK_TournamentAssignment_Assignment", "Assignment").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Assignment in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Assignment> AssignmentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Assignment>("MoCSModel.FK_TournamentAssignment_Assignment", "Assignment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Assignment>("MoCSModel.FK_TournamentAssignment_Assignment", "Assignment", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for AssignmentEnrollment in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_AssignmentEnrollment_TournamentAssignment", "AssignmentEnrollment")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<AssignmentEnrollment> AssignmentEnrollment
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<AssignmentEnrollment>("MoCSModel.FK_AssignmentEnrollment_TournamentAssignment", "AssignmentEnrollment");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<AssignmentEnrollment>("MoCSModel.FK_AssignmentEnrollment_TournamentAssignment", "AssignmentEnrollment", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Submit in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_Submit_TournamentAssignment", "Submit")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<Submit> Submit
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<Submit>("MoCSModel.FK_Submit_TournamentAssignment", "Submit");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<Submit>("MoCSModel.FK_Submit_TournamentAssignment", "Submit", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for Tournament in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MoCSModel", "FK_TournamentAssignment_Tournament", "Tournament")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Tournament Tournament
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tournament>("MoCSModel.FK_TournamentAssignment_Tournament", "Tournament").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tournament>("MoCSModel.FK_TournamentAssignment_Tournament", "Tournament").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Tournament in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Tournament> TournamentReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Tournament>("MoCSModel.FK_TournamentAssignment_Tournament", "Tournament");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Tournament>("MoCSModel.FK_TournamentAssignment_Tournament", "Tournament", value);
                }
            }
        }
    }
}
