//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30118.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoCS.WebDynamicDataAdmin
{


    public partial class Default_InsertEntityTemplate
    {

        protected global::System.Web.DynamicData.EntityTemplate EntityTemplate1;

        protected global::System.Web.DynamicData.DynamicControl DynamicControl;
    }
}
