//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30118.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoCS.WebDynamicDataAdmin
{


    public partial class ManyToManyField
    {

        protected global::System.Web.UI.WebControls.Repeater Repeater1;
    }
}
