// <auto-generated />
namespace MoCS.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class TeamIdnullable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeamIdnullable));
        
        string IMigrationMetadata.Id
        {
            get { return "201402181814116_TeamId-nullable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
