//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoCS.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentEnrollment
    {
        public AssignmentEnrollment()
        {
            this.Submits = new HashSet<Submit>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TournamentAssignment TournamentAssignment { get; set; }
        public virtual ICollection<Submit> Submits { get; set; }
        public virtual Team Team { get; set; }
    }
}
