//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoCS.Data.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoCSContainer : DbContext
    {
        public MoCSContainer()
            : base("name=MoCSContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tournament> Tournaments { get; set; }
        public virtual DbSet<Assignment> Assignments { get; set; }
        public virtual DbSet<TournamentAssignment> TournamentAssignments { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<Submit> Submits { get; set; }
        public virtual DbSet<AssignmentEnrollment> AssignmentEnrollments { get; set; }
    }
}
