//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoCS.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submit
    {
        public int Id { get; set; }
        public System.DateTime SubmitDateTime { get; set; }
        public int Status { get; set; }
        public System.DateTimeOffset TimeSinceEnrollment { get; set; }
        public string ProcessingDetails { get; set; }
        public string FileName { get; set; }
        public string FileContents { get; set; }
        public byte[] FileData { get; set; }
        public System.DateTime LastModified { get; set; }
    
        public virtual AssignmentEnrollment AssignmentEnrollment { get; set; }
        public virtual Team Team { get; set; }
    }
}
