//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoCS.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TournamentAssignment
    {
        public TournamentAssignment()
        {
            this.AssignmentEnrollments = new HashSet<AssignmentEnrollment>();
        }
    
        public int Id { get; set; }
        public int AssignmentOrder { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    
        public virtual Tournament Tournament { get; set; }
        public virtual Assignment Assignment { get; set; }
        public virtual ICollection<AssignmentEnrollment> AssignmentEnrollments { get; set; }
    }
}
