//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoCS.Data.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        public Tournament()
        {
            this.TournamentAssignments = new HashSet<TournamentAssignment>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateDateTime { get; set; }
    
        public virtual ICollection<TournamentAssignment> TournamentAssignments { get; set; }
    }
}
